spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taco_cloud
    username: anger
    password : anger
    driver-class-name: org.postgresql.Driver
    schema:
    - shema.sql
    data:
    - data.sql
  # spring data rest api base path
  data:
    rest:
      base-path: /data-api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
    kafka:
      producer:
        bootstrap-servers:
        - localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
        bootstrap-servers:
        - localhost:9092
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

server:
  port: 8091

logging:
  file:
    path: /var/logs/
    file: TacoCloud.log
  level:
    root: INFO
    org.springframework.security: DEBUG

taco:
  orders:
    pageSize: 10

# 设置 spring boot actuator
management:
  endpoints:
    web:
      base-path: /actuator
      # 设置对外暴露的端点
      exposure:
        include: '*'
        exclude: heapdump
  endpoint:
    health:
      show-details: always

info:
  github:
    repo: learn-spring